### ISSUE TITLE
Update ArticleCarouselItem and TopicsCarouselItem to include `compact` versions, `headingLevel` prop, and improved label

### ISSUE THREAD

**Issue by stephiescastle** [nasa-jpl/explorer-1#58]
[This PR on www-frontend](https://github.com/nasa-jpl/www-frontend/pull/1162) introduces a couple more styles for ArticleCarouselItem and TopicsCarouselItem. We should also show these variants in storybook. This change does not affect `scss` files. The `compact` style is achieved by conditionally applying inline classes.

### Tasks
- [ ] add `compact` style for `ArticleCarouselItem` and `TopicsCarouselItem`
- [ ] add options for `headingLevel` to `ArticleCarouselItem` and `TopicsCarouselItem`
- [ ] add `divide-x` and date styling
